name: Fairy

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Generate random commits
        run: |
          # Generate a random number of commits for the day (e.g., between 5 and 20)
          RANDOM_COMMITS=$((RANDOM % 16 + 5))  # Minimum 5 commits, maximum 20
          echo "Number of commits today: $RANDOM_COMMITS"

          # Create commits in quick succession
          for ((i=1; i<=RANDOM_COMMITS; i++)); do
            # Generate a unique empty commit with a timestamp
            git commit --allow-empty -m "Automated commit #$i: $(date +'%Y-%m-%d %H:%M:%S')"
          done

      - name: Push commits to repository
        run: |
          git push origin master
